-- MenuClean Table
select GROUP_CONCAT(CONCAT("'",COLUMN_NAME,"'"))
from INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'MenuClean'
AND TABLE_SCHEMA = 'NYCMenu'
order BY ORDINAL_POSITION
;

-- MenuPageClean Table
select GROUP_CONCAT(CONCAT("'",COLUMN_NAME,"'"))
from INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'MenuPageClean'
AND TABLE_SCHEMA = 'NYCMenu'
order BY ORDINAL_POSITION
;

-- MenuItemClean Table
select GROUP_CONCAT(CONCAT("'",COLUMN_NAME,"'"))
from INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'MenuItemClean'
AND TABLE_SCHEMA = 'NYCMenu'
order BY ORDINAL_POSITION
;

-- DishClean Table
select GROUP_CONCAT(CONCAT("'",COLUMN_NAME,"'"))
from INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'DishClean'
AND TABLE_SCHEMA = 'NYCMenu'
order BY ORDINAL_POSITION
;